version: '3.7'

services:
  db:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokemon
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongo:/data/db